"""Create the initial CAssist schema.

Revision ID: 7d82db2b0fe4
Revises:
Create Date: 2026-08-11 23:53:20.803559
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "7d82db2b0fe4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("external_auth_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_auth_id"),
    )
    op.create_index(
        "users_email_lower_idx", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "audit_events_workspace_created_idx",
        "audit_events",
        ["workspace_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.CHAR(length=64), nullable=True),
        sa.Column("r2_object_key", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "upload_pending",
                "uploaded",
                "processing",
                "ready",
                "failed",
                name="document_status",
            ),
            server_default="upload_pending",
            nullable=False,
        ),
        sa.Column("upload_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_deleted_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("byte_size > 0", name="documents_byte_size_positive"),
        sa.CheckConstraint(
            "original_deleted_at IS NULL OR "
            "(r2_object_key IS NULL AND original_deleted_by IS NOT NULL)",
            name="documents_original_deletion_consistent",
        ),
        sa.CheckConstraint(
            "page_count IS NULL OR page_count > 0", name="documents_page_count_positive"
        ),
        sa.ForeignKeyConstraint(
            ["original_deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "documents_workspace_created_idx",
        "documents",
        ["workspace_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "documents_workspace_sha256_idx",
        "documents",
        ["workspace_id", "sha256"],
        unique=True,
        postgresql_where=sa.text("sha256 IS NOT NULL"),
    )
    op.create_table(
        "workspace_members",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("owner", "admin", "member", name="member_role"),
            server_default="member",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )
    op.create_table(
        "processing_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider", postgresql.ENUM("openai", "gemini", name="model_provider"), nullable=False
        ),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("preprocessing_version", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "queued",
                "preprocessing",
                "extracting",
                "validating",
                "succeeded",
                "failed",
                "cancelled",
                name="run_status",
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message_safe", sa.Text(), nullable=True),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt_count >= 0", name="processing_runs_attempt_count_nonnegative"),
        sa.CheckConstraint(
            "estimated_cost_usd IS NULL OR estimated_cost_usd >= 0",
            name="processing_runs_estimated_cost_nonnegative",
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name="processing_runs_input_tokens_nonnegative",
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name="processing_runs_output_tokens_nonnegative",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "processing_runs_queue_idx",
        "processing_runs",
        ["queued_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "processing_runs_success_cache_idx",
        "processing_runs",
        [
            "document_id",
            "provider",
            "model_id",
            "prompt_version",
            "schema_version",
            "preprocessing_version",
        ],
        unique=True,
        postgresql_where=sa.text("status = 'succeeded'"),
    )
    op.create_table(
        "extraction_results",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("processing_run_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.Text(), nullable=False),
        sa.Column("raw_provider_output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("canonical_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "validation_issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            postgresql.ENUM("unreviewed", "in_review", "approved", name="review_status"),
            server_default="unreviewed",
            nullable=False,
        ),
        sa.Column("reviewed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["processing_run_id"], ["processing_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("processing_run_id"),
    )
    op.create_index(
        "extraction_results_canonical_gin_idx",
        "extraction_results",
        ["canonical_data"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "extraction_results_document_type_idx",
        "extraction_results",
        ["document_type"],
        unique=False,
    )
    op.create_table(
        "corrections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("extraction_result_id", sa.UUID(), nullable=False),
        sa.Column("corrected_by_user_id", sa.UUID(), nullable=False),
        sa.Column("field_path", sa.Text(), nullable=False),
        sa.Column("previous_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("corrected_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["corrected_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["extraction_result_id"], ["extraction_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "corrections_result_created_idx",
        "corrections",
        ["extraction_result_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "export_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("extraction_result_id", sa.UUID(), nullable=False),
        sa.Column("exported_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "format",
            postgresql.ENUM("json", "csv", "xlsx", "tally_json", name="export_format"),
            nullable=False,
        ),
        sa.Column("exporter_version", sa.Text(), nullable=False),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exported_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["extraction_result_id"], ["extraction_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "export_events_result_created_idx",
        "export_events",
        ["extraction_result_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("export_events_result_created_idx", table_name="export_events")
    op.drop_table("export_events")
    op.drop_index("corrections_result_created_idx", table_name="corrections")
    op.drop_table("corrections")
    op.drop_index("extraction_results_document_type_idx", table_name="extraction_results")
    op.drop_index(
        "extraction_results_canonical_gin_idx",
        table_name="extraction_results",
        postgresql_using="gin",
    )
    op.drop_table("extraction_results")
    op.drop_index(
        "processing_runs_success_cache_idx",
        table_name="processing_runs",
        postgresql_where=sa.text("status = 'succeeded'"),
    )
    op.drop_index(
        "processing_runs_queue_idx",
        table_name="processing_runs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("processing_runs")
    op.drop_table("workspace_members")
    op.drop_index(
        "documents_workspace_sha256_idx",
        table_name="documents",
        postgresql_where=sa.text("sha256 IS NOT NULL"),
    )
    op.drop_index("documents_workspace_created_idx", table_name="documents")
    op.drop_table("documents")
    op.drop_index("audit_events_workspace_created_idx", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("workspaces")
    op.drop_index("users_email_lower_idx", table_name="users")
    op.drop_table("users")
    op.execute("DROP TYPE export_format")
    op.execute("DROP TYPE review_status")
    op.execute("DROP TYPE run_status")
    op.execute("DROP TYPE model_provider")
    op.execute("DROP TYPE member_role")
    op.execute("DROP TYPE document_status")
    # ### end Alembic commands ###
